include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    avoid_redundant_argument_values: true
    directives_ordering: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    use_super_parameters: true
    package_api_docs: true

    avoid_print: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_final_locals: true
    sized_box_for_whitespace: true
    unnecessary_statements: true
    use_build_context_synchronously: true

    avoid_unnecessary_containers: true
    use_full_hex_values_for_flutter_colors: true
    
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    unnecessary_late: true
    unnecessary_new: true
    
    depend_on_referenced_packages: true
    secure_pubspec_urls: true
    sort_pub_dependencies: true