name: blutut_clasic
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  bluetooth_classic:
    path: pkgs/bluetooth_classic
  qr_flutter: ^4.1.0
  flutter_esc_pos_utils: ^1.0.1
  image: ^4.5.2
  shared_preferences: ^2.5.2
  auto_route: ^9.3.0+1
  auto_route_generator: ^9.3.1
  dio: ^5.8.0+1
  get_it: ^8.0.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
