name: blutut_clasic
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1
workspace: 
  - pkgs/bluetooth_classic

dependencies:
  auto_route: ^8.0.3
  bloc: ^9.0.0
  bluetooth_classic:
    path: pkgs/bluetooth_classic
  dio: ^5.8.0+1
  dotted_line: ^3.2.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_esc_pos_utils: ^1.0.1
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.5.2
  meta: ^1.15.0
  pdf: ^3.11.3
  printing: ^5.14.2
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.2

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/